Error: adding bitmap images on background
Images were able to be added to the background, but when those images
were added the event listeners was disabled for all clicks on the page.